posts/urls.py
from django.conf.urls import url
from . import views
app_name='posts'
urlpatterns=[

url(r'^$',views.PostList.as_view(),name='all'),
url(r'new/$',views.CreatePost.as_view(),name='create'),
url(r'by/(?P<username>[-\w]+)',views.UserPosts.as_view(),name='for_user'),
url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete')
]

simpleproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='group'))

]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from groups.models import Group
from  django.contrib.auth import get_user_model
User=get_user_model()

class Post(models.Model):
    user=models.ForeignKey(User,related_name='posts',on_delete=models.PROTECT,unique=True)
    created_at=models.DateTimeField(auto_now=True)
    message=models.TextField(unique=True)
    message_html=models.TextField(editable=False)
    group=models.ForeignKey(Group,related_name='posts',null=True,blank=True,on_delete=models.PROTECT)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        # self.message_html=misaka.html(self.message
        super().save(*args,**kwargs)

    def get_success_url(self):
        return reverse('groups:single',kwargs={'slug':self.object.slug})



    class Meta:
        ordering=['-created_at']
        unique_together=['user','message']






# Create your models here.

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from  django.http import Http404
from django.views import generic
from django.urls import reverse_lazy
from braces.views import SelectRelatedMixin
from .import models
from .import forms
from django.contrib.auth import get_user_model
from django.contrib import messages

class PostList(SelectRelatedMixin,generic.ListView):
    model=models.Post
    select_relate=('user','group')


class UserPosts(generic.ListView):
    model=models.Post
    template_name='posts/user_posts_list.html'

    def get_queryset(self):
        try:
            self.post_user=User.objects.prefetch_related('posts').get(username_iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return  self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['post_user']=self.post_user
        return context


class PostDetail(SelectRelatedMixin,generic.DetailView):
        model=models.Post
        select_related=('user','group')
        def get_queryset(self):
            queryset=super().get_queryset()
            return queryset.filter(user_name_iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields=('message','group')
    model=models.Post

    def form_valid(self,form):
        self.object=form.save(commit=False)
        self.object.user=self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model=models.Post
    select_related=('user','group')
    success_url=reverse_lazy('posts:all')

    def get_queryset(self):
        queryset=super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)


    def delete(self,*args,**kwargs):
        messages.success(self.request,'post deleted')
        return super().delete(*args,**kwargs)



# Create your views here.

posts/templates/posts/_post.html
<h3>{{post.message_html|safe}}</h3>
<h5>
<span>
<a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a></span>
<time>
<a href="{% url 'posts:single' username=post.user.username  pk=post.pk %}">{{post.created_at}}</a></time>
</h5>

{%if user.is_authenticated and post.user==user %}
<a href="{% url 'posts:delete' pl=post.pk %}" title=delete>Delete</a>
{% endif %}
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/posts_base.html" %}
{% load bootstrap3 %}
{% block post_content %}
<h4>create a new post</h4>
<form  action="{%  url 'posts:create' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit"  value="post">

</form>
{%  endblock %}

posts/templates/posts/posts_base.html
{% extends "base.html" %}
{% block content %}
<div class="posts-page">
<div class="container">
  <div class="row">
      {% block pregroup %}{% endblock %}
      {% block post_content %}{% endblock %}
      {% block post_post %}{% endblock %}
  </div>
</div>
</div>
{% endblock %}

posts/templates/posts/posts_create_del.html
{% extends "posts/posts_base.html "%}
{% block post_content %}
<h3>Are You Sure You Want To Delete </h3>
{% include "posts/_post.html" with post=object  hide_delete=True %}
<form  method="post">
<input type="submit" value="confrim delete">
<a href="{% url 'posts:single' username=user.username pk=object.pk %}">cancel</a>
</form>
{% endblock %}

posts/templates/posts/posts_detail.html
{% extends "posts/posts_base.html" %}
{% block post_content %}
{% include "posts/_post.html" %}
{% endblock %}

posts/templates/posts/posts_list.html
{% extends "posts/posts_base.html" %}
{% block pre_post_content %}
{% if request.user.is_authenticated %}
<ul>
  {% for member_group in get_user_groups %}
  <li><a href="{% utl 'groups:single' slug=member_group.group.slug %}"></a>
    </li>
  {% endfor %}
</ul>
{% endif %}
<h5>All groups</h5>
<ul>
{% for  other_group in get_other_groups %}
<li><a href="{%url 'group:single'slug=other_group.slug %}"></a>
  </li>
  {%e endfor %}
  </ul>
{% endblock %}
{% block post_content %}
{% for post in posts_list %}
{% include "posts/_post.html" %}
{% endfor %}
{% endblock %}

posts/templates/posts/user_posts_list.html
{% extends "posts/posts_base.html" %}
{% block prepost %}
<h1>@{{post_user.username}}</h1>
{% endblock %}
{% block post_content %}
{% for post in post_list %}
{% include "posts/_post.html" %}
{% endfor %}
{% endblock %}